### PR TITLE
[PCFG-9] api-config app service

### PR DESCRIPTION
**Pull request by jacopocarlini**
### List of changes

- added new app service for api-config
- added new api product api-config
- added new api for api-config product

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### CODE REVIEW

**Review by pasqualedevita — CHANGES_REQUESTED** [review]
1. to use a link to a openapi/swagger definition maybe it's better to point to a github raw url
2. using `10.1.240.16/29` we have a few ips to scale out this service (maybe it isn't a requirement)

**Comment by pasqualespica** [comment]
> 1. to use a link to a openapi/swagger definition maybe it's better to point to a github raw url (using app service link we have a chicken eggs problem :) )
> 2. using `10.1.240.16/29` we have a few ips to scale out this service (maybe it isn't a requirement)

they were both my suggestions 
1. the first one was to point out automatically to openspec definition. @jacopocarlini we use as suggested by @pasqualedevita raw file on github
2. it is exactly not a requirement ( no scale out, only internal use )

**Review by pasqualedevita — CHANGES_REQUESTED** [review]
api-config should be inside vnet_integration

**Comment by pasqualespica** [comment]
> api-config should be inside vnet_integration



> api-config should be inside vnet_integration

right, modified

**Review by pasqualespica — APPROVED** [review]

**Review by pasqualedevita — APPROVED** [review]

**Review by pasqualedevita — APPROVED** [review]

**Pull request merged**
