### PR TITLE
[PCFG-144] Api Config Update policy 

### PR DESCRIPTION
**Pull request by jacopocarlini**
### List of changes

- updated policy

### Type of changes

- [ ] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### CODE REVIEW

**Review by pasqualespica — DISMISSED** [review]
👍

**Comment by jacopocarlini** [comment]
@pasqualespica can you merge this PR?

**Review by pasqualedevita — COMMENTED** [review]
do u implement this check in api config?

**Comment by jacopocarlini** [comment]
@pasqualedevita we decided to remove this check

**Pull request merged**
